### ISSUE TITLE
Crash on non-ASCII input

### ISSUE THREAD

**Issue by offby1** [offby1/pyramid-tinyurl-doodle#2]
This url `http://localhost:6543/shorten-/?input_url=http%3A%2F%2Fwot%C2%AB%2Feva` led to

```
2015-10-10 22:32:29,619 ERROR [waitress][Dummy-4] Exception when serving /shorten-/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/usr/local/lib/python2.7/dist-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/usr/local/lib/python2.7/dist-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/usr/local/lib/python2.7/dist-packages/paste/translogger.py", line 69, in __call__
    return self.application(environ, replacement_start_response)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 242, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 217, in invoke_subrequest
    response = handle_request(request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid_tm/__init__.py", line 94, in tm_tween
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/dist-packages/pyramid_tm/__init__.py", line 75, in tm_tween
    response = handler(request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/usr/local/lib/python2.7/dist-packages/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/usr/local/lib/python2.7/dist-packages/tinyurl-0.0-py2.7.egg/tinyurl/views.py", line 99, in create_GET
    hash_object = hashlib.sha256(long_url)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xab' in position 10: ordinal not in range(128)
```

**Comment by offby1** [comment]
This appears to already have been fixed, in 5abc487cfda47e5260951a20d3d790dfd49fdd55
